---
- name: Install Nginx package
  package:
    name: "{{nginx_pkg_name}}"
    state: present
    update_cache: yes

- name: Template of nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{nginx_dir}}/nginx.conf"
    mode: 0644
  vars:
    cfgdir: "{{nginx_dir}}"
    user: "{{nginx_user}}"
    logdir: "{{nginx_logdir}}"
    pidfile: "{{nginx_pidfile}}"
  notify: Restart_nginx.service

- name: Copy server.crt and server.key
  copy:
    src: "{{item}}"
    dest: "{{nginx_dir}}/"
    mode: 0600
  with_items:
    - server.crt
    - server.key
  notify: Restart_nginx.service

- name: Template of default.conf
  template:
    src: default.conf.j2
    dest: "{{nginx_dir}}/conf.d/default.conf"
    mode: 0644
  vars:
    cfgdir: "{{nginx_dir}}"
    logdir: "{{nginx_logdir}}"
    locations: "{{nginx_locations}}"
  notify: Restart_nginx.service

- name: Template of server.conf
  template:
    src: server.conf.j2
    dest: "{{nginx_dir}}/conf.d/server.conf"
    mode: 0644
  vars:
    port: "{{nginx_extra_server.port}}"
    server_name: "{{nginx_extra_server.server_name}}"
    docroot: "{{nginx_extra_server.docroot}}"
    logdir: "{{nginx_logdir}}"
    log_locations: "{{nginx_log_locations}}"
  when: nginx_extra_server|length > 0
  notify: Restart_nginx.service

- name: Set read permission on logdir
  file:
    path: "{{nginx_logdir}}"
    state: directory
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of nginx.monit
  template:
    src: nginx.monit.j2
    dest: "{{monit_includedir}}/nginx.monit"
    mode: 0644
  vars:
    start_program: '/usr/bin/systemctl start nginx'
    stop_program: '/usr/bin/systemctl stop nginx'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service

- include: selinux.yml
  when: ansible_distribution in ['RedHat', 'CentOS'] and nginx_extra_server|length > 0
