---
- name: Allow Nginx to listen on tcp port
  seport:
    ports: "{{nginx_extra_server.port}}"
    proto: tcp
    setype: http_port_t
    state: present

- name: Allow Nginx to access the content tree
  sefcontext:
    target: "{{nginx_extra_server.docroot}}(/.*?)"
    setype: httpd_sys_content_t
    state: present
